# Configuración oficial de apoyo para Alenia Studios

github: Kaia-Alenia
patreon: alenia_studios
ko_fi: alenia_studios
custom: ['https://www.paypal.com/ncp/payment/TCCYMCFSVMV8E', 'https://alenia-studios.itch.io/']
